### ISSUE TITLE
Make a copy of an existing document

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#319] opened 2019-02-20 14:03 UTC
To be discussed.

**Comment by LBoyle** [comment] 2019-02-26 16:30
Duplicate of #268

**Comment by LBoyle** [comment] 2019-03-06 14:58
I'm going to start with placeholders first, then extend it to do the additional things needed for documents.

**Comment by LBoyle** [comment] 2019-03-07 18:01
I've made some good progress on lb-bugfix-319 branch
Populate the form with most of the metadata from an existing document. There are some bits I found tricky, but is doable.

**Comment by LBoyle** [comment] 2019-03-08 12:26
This is in PR 341

**Comment by allanchaplin** [comment] 2019-03-08 13:39
merged

**Closed by allanchaplin** 2019-03-08 13:39 UTC
Labels: _PR, enhancement
