### ISSUE TITLE
Changing Scale / Size via Metadata tab

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#141] opened 2019-01-11 16:50 UTC
Fails to update Scale / Size at under Metadata TAB - Documents have not been issued

![capture](https://user-images.githubusercontent.com/44202559/51047655-f633ba00-15c0-11e9-89ae-d31524671301.PNG)

![capture2](https://user-images.githubusercontent.com/44202559/51047656-f633ba00-15c0-11e9-87a5-4b889974dd48.PNG)

**Comment by LBoyle** [comment] 2019-01-14 10:59
I couldn't reproduce this. From the error there, it looks like one of three things. 
- The placeholder might have been created with incomplete metadata,
- The UI version was updated, and the provisioning script was not run on the CT sites, meaning it's trying to update a field that doesn't exist, 
- A field in the form was changed, then the text was deleted with backspace, and the empty string was sent in the request, which would be my fault, but I'm not sure this is the problem.

**Comment by LBoyle** [comment] 2019-01-14 12:00
I just had the same error on a different request, investigating.

**Comment by LBoyle** [comment] 2019-01-14 13:42
Found and fixed in PR #181

**Closed by LBoyle** 2019-01-14 13:42 UTC
