### ISSUE TITLE
Placeholder - inconsistent behaviour with title required

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#264] opened 2019-02-07 07:52 UTC
Title has the red * to show its required, the submit button is disabled until its filled.  Adding something to the title enables the submit button.  Delete the title and the submit button is still enabled, allowing you to add a placeholder without a title.

Is the title required?

**Comment by LBoyle** [comment] 2019-02-07 09:51
In theory, no not required. 
The issue is with the red asterisks, I didn't ever take the time to make sure they're right after all the big changes recently. So don't be surprised when they are wrong.

**Comment by LBoyle** [comment] 2019-02-07 10:23
https://github.com/nittygritty-uk/Atvero/pull/271

This removes the asterisk, did it because it was quick and easy

**Comment by LBoyle** [comment] 2019-02-11 12:34
This was merged, please make a new issue for related problems.

**Closed by LBoyle** 2019-02-11 12:34 UTC
