### ISSUE TITLE
Renditions not showing

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#161] opened 2019-01-16 15:37 UTC
Hello,

I uploaded 'Documents received into Docs area but the renditions are not showing. 

![capture](https://user-images.githubusercontent.com/44202559/51259667-8187c380-19a4-11e9-87be-33ae6b0f4c22.PNG)

**Comment by ng-marcus** [comment] 2019-01-16 15:46
Louis is investigating

**Comment by LBoyle** [comment] 2019-01-16 15:46
I think the batch uploader failed silently while performing the file upload. This is in the scope of my work today so I can get right on it.

**Comment by LBoyle** [comment] 2019-01-16 15:50
As a quick fix, you could select the document, and drag and drop the file again using the side-panel uploader.

**Comment by LBoyle** [comment] 2019-01-16 18:00
PR #187 
I found the spot and made sure the error that caused this issue is caught and displayed to the user. 
Next is to track down the cause of the inconsistency.

**Comment by LBoyle** [comment] 2019-01-31 14:35
I haven't seen this since the attempted fix, I suspect it was only because we were failing silently. Not the failure isn't silent, it gets caught, and we don't get into the broken state.

**Comment by LBoyle** [comment] 2019-01-31 14:36
I haven't seen this since the attempted fix, I suspect it was only because we were failing silently. Not the failure isn't silent, it gets caught, and we don't get into the broken state.

Closing until it happens again, in which case, please open a new issue.

**Closed by LBoyle** 2019-01-31 14:36 UTC
Labels: bug
