### ISSUE TITLE
Contacts: Some forms allow you to submit with incomplete input

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#231] opened 2019-02-04 11:51 UTC
New address form can be submitted without filling it in completely. 
I suspect this happens in other places as well.

**Comment by jim80** [comment] 2019-02-05 15:21
I cannot reproduce this with CreateAddress.re - the submit button is disabled until there is something in each required field.
That's not to say this is the case with other forms.of course.

**Comment by jim80** [comment] 2019-02-06 17:35
Still noticed any of these. Any chance you can reproduce one Louis? You'll then have the chance to see me eating my hat ;)

**Comment by jim80** [comment] 2019-02-06 17:37
Assigned it to you for feedback only, assign it back to me when and if answered and I'll see what I can do to fix, if it needs it.

**Comment by LBoyle** [comment] 2019-02-06 18:01
No can't reproduce, I don't remember the circumstances

**Comment by jim80** [comment] 2019-02-06 18:06
No problem!
To close or not to close? This is the question.

**Comment by jim80** [comment] 2019-02-07 10:16
Aha - in fact CreateCompany was not validating City, though that is a funny one since it didn't have city before I patched it up to do so!

**Comment by jim80** [comment] 2019-02-07 10:16
I've now fixed that one...

**Comment by LBoyle** [comment] 2019-02-07 10:37
Righto

**Comment by jim80** [comment] 2019-02-07 12:38
OK, checked them all, all looks now. Will close when PR merged...

**Comment by jim80** [comment] 2019-02-08 14:29
Done and PR merged...

**Closed by jim80** 2019-02-08 14:29 UTC
Labels: _in progress, bug
