### ISSUE TITLE
Bulk Upload - rejects CT style named file without category with an incorrect message

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#75] opened 2018-12-06 08:44 UTC
For file `RG103-CUR-02-01-DR-S-211` it says the number should be 3 digits, when in fact the category is missing.

**Comment by LBoyle** [comment] 2019-01-02 17:05
In this case, it thinks that category is 21 and number is 1, I suspect this is still the case. Not sure how to fix this, as 21 is a valid category.

**Comment by LBoyle** [comment] 2019-01-04 14:50
Closing without further action. 
Technically in this case, the problem is with the number, if you look at the templates, because number is the compound of category and number, the error message is correct. 
I removed the "should be 3 digits" and just say there's a problem with the number.

**Closed by LBoyle** 2019-01-04 14:50 UTC
Labels: DLM, bug
