### ISSUE TITLE
Contact not opening bug

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#37] opened 2018-11-21 15:40 UTC
Uncaught TypeError: Cannot read property 'webPartTag' of undefined
    at t._asyncRenderTimeout (spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-09.009/sp-webpart-base_en-us_5f14b06f692e578afed8e8e294197ada.js:84)
    at spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-09.009/sp-webpart-base_en-us_5f14b06f692e578afed8e8e294197ada.js:84
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 (Invalid instrumentation key)

**Comment by allanchaplin** [comment] 2018-11-21 16:39
Hi Stephen,

Is this error a one time thing or it happening all the time?  If its all the time can you paste the url of the page so I can test.

Thanks,

Allan

**Comment by StephenHiggon01** [comment] 2018-11-21 16:46
Happens all the time

https://chapmantaylorspace.sharepoint.com/sites/C049KAM/SitePages/Contacts.aspx


Stephen Higgon
Document Manager
shiggon@chapmantaylor.com

**Comment by allanchaplin** [comment] 2018-11-22 12:30
After discussion with Stephen this is a duplicate of #11

**Comment by ng-marcus** [comment] 2019-01-02 21:09
Closed as duplicate, actual issue is the double click

**Closed by ng-marcus** 2019-01-02 21:09 UTC
