### ISSUE TITLE
Adding Placeholder DLM - 

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#55] opened 2018-11-23 10:24 UTC
Created a Placeholder, created one straight after. I enter '21' into Category. Clicked submit. The system failed the action 'Must selected category' Selected 21 properly so the text is showing. System will not now submit. 

![image](https://user-images.githubusercontent.com/44202559/48938726-f80ac680-ef09-11e8-80d6-eb16f963a8d3.png)

**Comment by LBoyle** [comment] 2018-11-23 11:32
Hi Stephen, we can't reproduce this here, can you reproduce it consistently? 

It's possible that you tabbed through the dropdowns without selecting anything, I do this frequently.

**Comment by StephenHiggon01** [comment] 2018-11-23 11:37
Hi Louis, I did type 21 and tab on so click to select.

02073717106

Please add me to Skype as well so I can screen share with you.

Thanks,

Stephen Higgon
Document Manager
shiggon@chapmantaylor.com

**Comment by LBoyle** [comment] 2018-11-23 11:48
Hi again Stephen,

I meant to say the other dropdowns above, not the category selector. 

I gave you a ring, but got no answer, I'm +447788269168. 
Don't rush to get back to me, code is frozen for a demo at the moment. 
Also I use Linux for work, and haven't set up Skype, I've never had a need for it, but I'll get it up and running this weekend so I'll be more accessible.

**Comment by StephenHiggon01** [comment] 2018-11-23 11:55
Ok thanks Louis. Let me know when you are up and running again

Stephen Higgon
Document Manager
shiggon@chapmantaylor.com

**Comment by ng-marcus** [comment] 2019-01-02 16:43
Resolved with new UI

**Closed** 2019-01-02 16:43 UTC
